create database agenda_mg;
use agenda_mg;

create table Eventos;

select * from Eventos;

select * from admin;

drop table usuarios;

drop table admin;

INSERT INTO Eventos 
(nome_evento, descricao_do_evento, data_do_evento, local_do_evento, preco_do_evento, capacidade_de_pessoas_no_evento, tipo_do_evento, apresentador_do_evento, duracao_do_evento)
VALUES 
('Show Sertanejo no Parque Centenário', 
'Apresentação de duplas sertanejas locais em uma noite de muita música e diversão.', 
'2025-11-15', 
'Parque Centenário de Mogi das Cruzes - Av. Francisco Rodrigues Filho, 1500', 
50.00, 
4000, 
'Show', 
'Pedro & Rafa', 
'4 horas'),

('Palestra sobre Empreendedorismo Jovem', 
 'Dicas e estratégias para jovens que desejam abrir o próprio negócio.', 
 '2025-10-20', 
 'Auditório da Universidade de Mogi das Cruzes (UMC)', 
 40.00, 
 300, 
 'Palestra', 
 'Camila Duarte', 
 '2 horas'),

('Workshop de Fotografia Urbana', 
 'Aprenda técnicas de fotografia em ambientes urbanos com prática em campo.', 
 '2025-11-02', 
 'Centro Cultural de Mogi das Cruzes - Rua José Bonifácio, 516', 
 80.00, 
 80, 
 'Workshop', 
 'Lucas Carvalho', 
 '4 horas'),

('Espetáculo Teatral: Amor em Cena', 
 'Comédia romântica encenada por artistas mogianos.', 
 '2025-12-01', 
 'Theatro Vasques - Rua Dr. Corrêa, 515', 
 60.00, 
 500, 
 'Teatro', 
 'Cia Teatral Mogi em Cena', 
 '2 horas'),

('Corrida de Rua Mogi em Movimento', 
 'Evento esportivo com percursos de 5 e 10 km pelas principais avenidas da cidade.', 
 '2025-10-26', 
 'Largada na Av. Cívica, em frente ao Ginásio Municipal Hugo Ramos', 
 30.00, 
 2000, 
 'Esportivo', 
 'Prefeitura de Mogi das Cruzes', 
 '3 horas'),

('Festival Cultural de Primavera', 
 'Celebração da cultura mogiana com música, dança e gastronomia regional.', 
 '2025-11-10', 
 'Parque Botyra Camorim Gatti - Rua Otávio de Souza Franco, 85', 
 25.00, 
 1500, 
 'Cultural', 
 'Secretaria de Cultura de Mogi', 
 '6 horas'),

('Concerto Musical de Natal', 
 'Orquestra municipal apresenta canções natalinas e clássicos populares.', 
 '2025-12-20', 
 'Catedral de Santana - Praça Coronel Almeida, Centro', 
 40.00, 
 700, 
 'Musical', 
 'Orquestra Jovem de Mogi das Cruzes', 
 '2 horas'),

('Seminário Acadêmico de Sustentabilidade', 
 'Discussões sobre meio ambiente e práticas ecológicas urbanas.', 
 '2025-11-25', 
 'Auditório da UMC - Bloco D', 
 35.00, 
 400, 
 'Acadêmico', 
 'Prof. Dr. Ricardo Nunes', 
 '4 horas'),

('Festival Gastronômico Mogiano', 
 'Restaurantes locais oferecem pratos típicos e novas receitas autorais.', 
 '2025-12-05', 
 'Parque Centenário de Mogi das Cruzes', 
 20.00, 
 2000, 
 'Festival', 
 'Associação Gastronômica de Mogi', 
 '8 horas'),

('Feira de Artesanato e Economia Criativa', 
 'Exposição e venda de produtos artesanais produzidos na região.', 
 '2025-11-16', 
 'Praça Coronel Benedito Almeida - Centro Histórico', 
 10.00, 
 1000, 
 'Feira', 
 'Coletivo Arte Mogi', 
 '7 horas'),

('Show de Rock Local', 
 'Bandas independentes da região apresentam seus trabalhos autorais.', 
 '2025-11-22', 
 'Clube Náutico Mogiano - Av. Cívica, 500', 
 60.00, 
 1500, 
 'Show', 
 'Banda Som da Serra', 
 '3 horas'),

('Palestra: Tecnologia e Futuro Profissional', 
 'Especialistas debatem sobre carreiras na área de tecnologia e inovação.', 
 '2025-11-09', 
 'Espaço Sebrae Mogi das Cruzes - Av. Voluntário Fernando Pinheiro Franco, 350', 
 20.00, 
 200, 
 'Palestra', 
 'Eng. Felipe Andrade', 
 '2 horas'),

('Workshop de Programação Web', 
 'Aprenda HTML, CSS e JavaScript com desenvolvedores locais.', 
 '2025-11-18', 
 'Coworking MogiTech - Rua Hamilton da Silva e Costa, 50', 
 90.00, 
 50, 
 'Workshop', 
 'Gustavo Mendes', 
 '5 horas'),

('Peça Infantil: O Reino Encantado', 
 'Espetáculo infantil com personagens e músicas ao vivo.', 
 '2025-12-03', 
 'Theatro Vasques - Rua Dr. Corrêa, 515', 
 40.00, 
 400, 
 'Teatro', 
 'Grupo Cena Infantil', 
 '1 hora e 30 minutos'),

('Campeonato de Futebol Beneficente', 
 'Times locais jogam em prol de instituições de caridade da cidade.', 
 '2025-11-12', 
 'Estádio Municipal Francisco Ribeiro Nogueira (Nogueirão)', 
 15.00, 
 5000, 
 'Esportivo', 
 'Federação Esportiva de Mogi', 
 '6 horas'),

('Mostra Cultural de Dança', 
 'Apresentações de escolas e grupos de dança da região.', 
 '2025-10-30', 
 'Centro Cultural de Mogi das Cruzes - Rua José Bonifácio, 516', 
 25.00, 
 600, 
 'Cultural', 
 'Associação de Dança de Mogi', 
 '3 horas'),

('Festival de Música Popular Mogiana', 
 'Cantores e bandas da cidade competem em um grande festival.', 
 '2025-12-14', 
 'Parque Centenário de Mogi das Cruzes', 
 30.00, 
 3500, 
 'Musical', 
 'Secretaria de Cultura de Mogi', 
 '5 horas'),

('Semana Acadêmica de Psicologia', 
 'Palestras e atividades sobre comportamento humano e terapias modernas.', 
 '2025-11-27', 
 'Universidade de Mogi das Cruzes (UMC) - Bloco F', 
 50.00, 
 300, 
 'Acadêmico', 
 'Prof.ª Dra. Ana Souza', 
 '6 horas'),

('Festival de Cinema Mogiano', 
 'Exibição de curtas e longas-metragens produzidos na região.', 
 '2025-12-08', 
 'Cine Pateo Mogi Shopping - Av. Vereador Narciso Yague Guimarães, 1001', 
 25.00, 
 200, 
 'Festival', 
 'Coletivo CineMogi', 
 '4 horas'),

('Feira de Startups e Tecnologia', 
 'Empreendedores locais apresentam soluções inovadoras em tecnologia.', 
 '2025-12-18', 
 'Centro Municipal de Empreendedorismo - Rua Dr. Deodato Wertheimer, 200', 
 30.00, 
 800, 
 'Feira', 
 'Sebrae Alto Tietê', 
 '8 horas');

INSERT INTO admin (email, senha, nome) VALUES
('admin@agendamg.com', '$2a$12$WYdbsGjlIIl2ja9qxVQgE.nz3.blEyFcp5OgXPovHh7hXTMjir/JW', 'Administrador Principal');

create table IF NOT EXISTS admin (
    id int auto_increment primary key,
    email varchar(255) not null unique,
    senha varchar(255) not null,
    nome varchar(255) not null,
    data_criacao timestamp default CURRENT_TIMESTAMP,
    ativo boolean default TRUE,
    
    INDEX idx_email (email)
);
